### ISSUE TITLE
Factions 2.7.0

### ISSUE THREAD

**Issue by k3ldon** [webbukkit/Dynmap-Factions#15]
dont work with the last factions update

[06:46:50] [Server thread/WARN]: [Dynmap-Factions] Task #136 for Dynmap-Factions v0.81-37 generated an exception
java.lang.NoClassDefFoundError: com/massivecraft/factions/entity/FactionColls
    at org.dynmap.factions.DynmapFactionsPlugin.updateFactions(DynmapFactionsPlugin.java:474) ~[?:?]
    at org.dynmap.factions.DynmapFactionsPlugin.access$000(DynmapFactionsPlugin.java:49) ~[?:?]
    at org.dynmap.factions.DynmapFactionsPlugin$FactionsUpdate.run(DynmapFactionsPlugin.java:133) ~[?:?]
    at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-20141113a.bps.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-20141113a.bps.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:641) [spigot-20141113a.bps.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot-20141113a.bps.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot-20141113a.bps.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot-20141113a.bps.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot-20141113a.bps.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
Caused by: java.lang.ClassNotFoundException: com.massivecraft.factions.entity.FactionColls
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366) ~[?:1.7.0_72]
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_72]
    at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_72]
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_72]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-20141113a.bps.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-20141113a.bps.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_72]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_72]
    ... 10 more

**Comment by mikeprimm** [comment]
Just released update to d.b.o that should work with v2.7.1
