### ISSUE TITLE
Dynmap Factions not loading

### ISSUE THREAD

**Issue by CristianoBarone** [webbukkit/Dynmap-Factions#24]
```
 Task #100 for Dynmap-Factions v0.90-39 generated an exception
java.lang.NullPointerException: null
        at java.lang.String.replace(String.java:2240) ~[?:1.8.0_131]
        at org.dynmap.factions.DynmapFactionsPlugin.formatInfoWindow(DynmapFactionsPlugin.java:207) ~[?:?]
        at org.dynmap.factions.DynmapFactionsPlugin.handleFactionOnWorld(DynmapFactionsPlugin.java:312) ~[?:?]
        at org.dynmap.factions.DynmapFactionsPlugin.updateFactions(DynmapFactionsPlugin.java:507) ~[?:?]
        at org.dynmap.factions.DynmapFactionsPlugin.access$000(DynmapFactionsPlugin.java:49) ~[?:?]
        at org.dynmap.factions.DynmapFactionsPlugin$FactionsUpdate.run(DynmapFactionsPlugin.java:133) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

```

This is for both 0.90 and 0.91, server is running 1.12.2 with Factions 2.14 and Dynmap 3.1-beta4-421

**Comment by simsnet** [comment]
Do you have a faction without a description?  The plugin will throw an exception if an essential part of a faction has no info available, such as title, description, members, etc.

#22 references this.
