### ISSUE TITLE
Dynmap not showing factions

### ISSUE THREAD

**Issue by DrakeBD** [webbukkit/Dynmap-Factions#4]
Factions build v7.2.5beta 
dynmap build 39
dynmap factions build 0.18
Craftbukkit v1.2.5.R4.0RB

Factions overlay no longer shows on the dynmap could u please fix this issue for the latest factions as the new factions plugin even in beta is better than the previous

**Comment by terminal-case** [comment]
This does indeed seem to be the case with the latest Factions beta builds--the error generated is as follows:

23:11:05 [WARNING] Task of 'Dynmap-Factions' generated an exception
java.lang.ClassCastException: com.massivecraft.factions.struct.TerritoryAccess cannot be cast to java.lang.String
        at org.dynmap.factions.DynmapFactionsPlugin.updateFactions(DynmapFactionsPlugin.java:389)
        at org.dynmap.factions.DynmapFactionsPlugin.access$000(DynmapFactionsPlugin.java:37)
        at org.dynmap.factions.DynmapFactionsPlugin$FactionsUpdate.run(DynmapFactionsPlugin.java:112)
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:126)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:533)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:459)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)

**Comment by DrakeBD** [comment]
im not sure but i think the developer of this plugin is inactive have not seen a post from him in ages if that is the case we will try fix the issue ourselvs if we do we will add the link to the fixed plugin here it would have a different version number something like v0.19BD just so its clear its a quick fix from us and not the devs own release.
We shall see what we can do

**Comment by fouram** [comment]
@DrakeBD Seeing as there was a commit to this repo just today (6/18), I wouldn't say that the dev is inactive. Try building from the source code and see if the issue is fixed. If not, fix it and submit a Pull Request - don't fix it and release a separate version.

**Comment by mikeprimm** [comment]
Please check out the latest release (0.20)
